class profile::nodejs::process_central_js (
  $config_path          = '/opt/.configs/central-js',
  $node_env             = 'test-env',
  $debug                = false,
  $sServerRegion        = '',
  $server_protocol      = 'https',
  $server_port          = '8443',
  $server_key           = '',
  $server_crt           = '',
  $session_secret       = '',
  $session_key_one      = '',
  $session_key_two      = '',
  $session_secure       = true,
  $session_max_age      = '14400000',
  $activiti_protocol    = 'https',
  $activiti_hostname    = 'test.example.com',
  $activiti_port        = '8443',
  $activiti_path        = '/wf/service',
  $activiti_user        = 'some_user',
  $activiti_password    = '***************',
  $bankid_sprotocol_access_service  = 'https',
  $bankid_shost_access_service      = 'bankid.privatbank.ua',
  $bankid_sprotocol_resourc_service = 'https',
  $bankid_shost_resource_service    = 'bankid.privatbank.ua',
  $bankid_clientid      = '00000000-0000-0000-0000-000000000000',
  $bankid_client_secret = '***************************************************************************',
  $node_tls_reject_unauthorized     = 0,) {
  file { "$config_path/process.json":
    ensure  => 'present',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template("profile/nodejs/process_central_js.json.erb"),
  }
}
