class role::central_js (
  $os_username          = 'igov',
  $http_host_name       = 'central_js.example.com',
  $node_env             = 'test-env',
  $debug                = false,
  $sServerRegion        = 'https://test.example.com',
  $server_protocol      = 'https',
  $server_port          = '8443',
  $server_key           = 'puerez4kei2Zaise4shied5chechaiqu',
  $server_crt           = 'ee2Quah2eeno5vai8kuNaejohr7aizoo',
  $session_secret       = 'Ahgei1ogh3Ohyaengau5Ub2soo9osah9',
  $session_key_one      = 'tu7Ood6Aabahcur5eiso9oongaeshaiy',
  $session_key_two      = 'uawahph2AGoh6ez4zahwoophug2ahpah',
  $session_secure       = true,
  $session_max_age      = '14400000',
  $activiti_protocol    = 'https',
  $activiti_hostname    = 'test.example.com',
  $activiti_port        = '8443',
  $activiti_path        = '/wf/service',
  $activiti_user        = 'user08378a32',
  $activiti_password    = '***************',
  $bankid_sprotocol_access_service  = 'https',
  $bankid_shost_access_service      = 'bankid.privatbank.ua',
  $bankid_sprotocol_resourc_service = 'https',
  $bankid_shost_resource_service    = 'bankid.privatbank.ua',
  $bankid_clientid      = '00000000-0000-0000-0000-000000000000',
  $bankid_client_secret = '***************************************************************************',
  $node_tls_reject_unauthorized     = 0,) {
  class { "profile::nodejs::common": appuser => $os_username } ->
  profile::nodejs::app_dirs { "central-js": }

  class { "nginx::config::central_js": server_name => $http_host_name, }

  class { "profile::nodejs::process_central_js":
    node_env             => $node_env,
    debug                => $debug,
    sServerRegion        => $sServerRegion,
    server_protocol      => $server_protocol,
    server_port          => $server_port,
    server_key           => $server_key,
    server_crt           => $server_crt,
    session_secret       => $session_secret,
    session_key_one      => $session_key_one,
    session_key_two      => $session_key_two,
    session_secure       => $session_secure,
    session_max_age      => $session_max_age,
    activiti_protocol    => $activiti_protocol,
    activiti_hostname    => $activiti_hostname,
    activiti_port        => $activiti_port,
    activiti_path        => $activiti_path,
    activiti_user        => $activiti_user,
    activiti_password    => $activiti_password,
    bankid_sprotocol_access_service  => $bankid_sprotocol_access_service,
    bankid_shost_access_service      => $bankid_shost_access_service,
    bankid_sprotocol_resourc_service => $bankid_sprotocol_resourc_service,
    bankid_shost_resource_service    => $bankid_shost_resource_service,
    bankid_clientid      => $bankid_clientid,
    bankid_client_secret => $bankid_client_secret,
    node_tls_reject_unauthorized     => $node_tls_reject_unauthorized,
  }
}
